In [1]:
import pandas as pd

### 1. Clean Real Demand Data

##### 2024_year_data

In [103]:
# Load the files
real_year = pd.read_csv("./RealDemand_2024.csv", sep=';')
real_year.head()

     id         name  geoid  geoname         value                   datetime
0  1293  Real demand    NaN      NaN  21863.416667  2024-01-01T00:00:00+01:00
1  1293  Real demand    NaN      NaN  21200.666667  2024-01-01T01:00:00+01:00
2  1293  Real demand    NaN      NaN  20033.083333  2024-01-01T02:00:00+01:00
3  1293  Real demand    NaN      NaN  18867.666667  2024-01-01T03:00:00+01:00
4  1293  Real demand    NaN      NaN  18137.166667  2024-01-01T04:00:00+01:00

In [104]:
# Parse datetimes; handle timezone-aware strings by parsing with utc=True
real_year["datetime"] = pd.to_datetime(real_year["datetime"], errors="coerce", utc=True)
real_year["datetime"] = real_year["datetime"].dt.tz_convert("Europe/Madrid").dt.tz_localize(None)
real_year.head()

     id         name  geoid  geoname         value            datetime
0  1293  Real demand    NaN      NaN  21863.416667 2024-01-01 00:00:00
1  1293  Real demand    NaN      NaN  21200.666667 2024-01-01 01:00:00
2  1293  Real demand    NaN      NaN  20033.083333 2024-01-01 02:00:00
3  1293  Real demand    NaN      NaN  18867.666667 2024-01-01 03:00:00
4  1293  Real demand    NaN      NaN  18137.166667 2024-01-01 04:00:00

In [105]:
real_year = real_year[["datetime", "value"]].rename(columns={"value": "NLD"})
real_year.head()

             datetime           NLD
0 2024-01-01 00:00:00  21863.416667
1 2024-01-01 01:00:00  21200.666667
2 2024-01-01 02:00:00  20033.083333
3 2024-01-01 03:00:00  18867.666667
4 2024-01-01 04:00:00  18137.166667

In [106]:
real_year.tail()

                datetime           NLD
8779 2024-12-31 19:00:00  31136.333333
8780 2024-12-31 20:00:00  30291.666667
8781 2024-12-31 21:00:00  28500.250000
8782 2024-12-31 22:00:00  25583.500000
8783 2024-12-31 23:00:00  24053.416667

In [107]:
# delete rows of last day (2024-12-31)
real_year = real_year[real_year["datetime"].dt.date != pd.to_datetime("2024-12-31").date()]
real_year.tail()

                datetime           NLD
8755 2024-12-30 19:00:00  32269.333333
8756 2024-12-30 20:00:00  32806.250000
8757 2024-12-30 21:00:00  32516.666667
8758 2024-12-30 22:00:00  30309.833333
8759 2024-12-30 23:00:00  27405.333333

In [108]:
# delete rows with same datetime, keep the first occurrence
real_year = real_year.drop_duplicates(subset=["datetime"], keep="first")

In [109]:
# Format to match demand.csv
# First two header rows as in demand.csv
header = pd.DataFrame({"nodes": ["techs"], "NLD": ["demand_power"]})

# Prepare final formatted time series
ts = pd.DataFrame({
    "nodes": real_year["datetime"].dt.strftime("%Y-%m-%d %H:%M:%S"),
    "NLD": real_year["NLD"]
})

# Combine them together
real_demand_year = pd.concat([header, ts], ignore_index=True)

# Save to new CSV
real_demand_year.to_csv("./demand_year.csv", index=False)

real_demand_year.head(10)

                 nodes           NLD
0                techs  demand_power
1  2024-01-01 00:00:00  21863.416667
2  2024-01-01 01:00:00  21200.666667
3  2024-01-01 02:00:00  20033.083333
4  2024-01-01 03:00:00  18867.666667
5  2024-01-01 04:00:00  18137.166667
6  2024-01-01 05:00:00  17881.166667
7  2024-01-01 06:00:00  18059.166667
8  2024-01-01 07:00:00  18429.333333
9  2024-01-01 08:00:00  18439.333333

In [110]:
# find the mean of NLD
mean_demand = real_year["NLD"].mean()
mean_demand

26442.079289873273

In [125]:
demand_2030 = 35447
ratio = demand_2030 / mean_demand

# scale the NLD values
real_2030 = real_year.copy()
real_2030["NLD"] = real_2030["NLD"] * ratio

real_2030.head()

             datetime           NLD
0 2024-01-01 00:00:00  29309.061594
1 2024-01-01 01:00:00  28420.610312
2 2024-01-01 02:00:00  26855.403357
3 2024-01-01 03:00:00  25293.100932
4 2024-01-01 04:00:00  24313.827206

In [126]:
header = pd.DataFrame({"nodes": ["techs"], "NLD": ["demand_power"]})

# Prepare final formatted time series
ts = pd.DataFrame({
    "nodes": real_2030["datetime"].dt.strftime("%Y-%m-%d %H:%M:%S"),
    "NLD": real_2030["NLD"]
})

# Combine them together
real_demand_2030 = pd.concat([header, ts], ignore_index=True)

# Save to new CSV
real_demand_2030.to_csv("./demand_2030.csv", index=False)

real_demand_2030.head()

                 nodes           NLD
0                techs  demand_power
1  2024-01-01 00:00:00  29309.061594
2  2024-01-01 01:00:00  28420.610312
3  2024-01-01 02:00:00  26855.403357
4  2024-01-01 03:00:00  25293.100932

### 2. Clean Renewables Data

### Solar capacity factor data

In [5]:
# load PV capacity factor data from CSV
solar_cf = pd.read_csv("./PV_CF_2024.csv")
solar_cf.head()

C:\Users\yaowa\AppData\Local\Temp\ipykernel_30200\2381211353.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  solar_cf = pd.read_csv("./PV_CF_2024.csv")

,"# Renewables.ninja pv (country zones, hourly, 1980 - 2024) - ES - ninja-pv-countryzones-ES-hourly-merra2.csv.gz - Version: 1.4 - License: https://creativecommons.org/licenses/by-nc/4.0/ - Reference: https://doi.org/10.1016/j.energy.2016.08.060",Unnamed: 1
0,"# Units: time in UTC, other columns are bias-c...",NaN
1,"# {'units': {'time': 'UTC', 'NATIONAL': 'bias-...",NaN
2,time,NATIONAL
3,1980-01-01 00:00:00+00:00,0.000000
4,1980-01-01 01:00:00+00:00,0.000000

In [6]:
# drop first three rows
solar_cf = solar_cf.iloc[3:].reset_index(drop=True)

# change column names to datetime and CF_solar
solar_cf.columns = ["datetime", "CF_solar"]

# filter datatime between 2024-01-01 and 2024-12-31
solar_cf = solar_cf[(solar_cf["datetime"] >= "2024-01-01") & (solar_cf["datetime"] <= "2024-12-31")].reset_index(drop=True)
solar_cf.head()

                    datetime CF_solar
0  2024-01-01 00:00:00+00:00      0.0
1  2024-01-01 01:00:00+00:00      0.0
2  2024-01-01 02:00:00+00:00      0.0
3  2024-01-01 03:00:00+00:00      0.0
4  2024-01-01 04:00:00+00:00      0.0

### Wind capacity factor data

In [7]:
# load wind onshore capacity factor data from CSV
windonshore_cf = pd.read_csv("./WindOnshore_CF_2024.csv")
windonshore_cf.head()

C:\Users\yaowa\AppData\Local\Temp\ipykernel_30200\4013043967.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  windonshore_cf = pd.read_csv("./WindOnshore_CF_2024.csv")

,"# Renewables.ninja Wind (current onshore fleet, country zones, hourly, 1980 - 2024) - Spain - ninja_wind_countryzones_hourly_ES_current-onshore_merra2.csv - Version 1.4 - License: https://creativecommons.org/licenses/by-nc/4.0/ - Reference: https://doi.org/10.1016/j.energy.2016.08.068",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,# Units: time in UTC; other columns are capaci...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"# {'units': {'time': 'UTC', 'NATIONAL': 'bias-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,time,NATIONAL,ES11,ES12,ES13,ES21,ES22,ES23,ES24,ES30,...,ES42,ES43,ES51,ES52,ES53,ES61,ES62,ES63,ES64,ES70
3,1980-01-01 00:00:00+00:00,0.460166,0.409802,0.490627,0.685976,0.453296,0.279961,0.476468,0.485619,0.29944,...,0.48794,0.211598,0.124726,0.563356,0.10355,0.270761,0.48617,0.205465,0.6481,0.390197
4,1980-01-01 01:00:00+00:00,0.483027,0.372898,0.448044,0.713033,0.520734,0.408829,0.592286,0.583023,0.286953,...,0.459711,0.216962,0.162608,0.597692,0.094159,0.267149,0.504723,0.21085,0.611547,0.377099

In [8]:
# drop first three rows, and keep only first two columns
windonshore_cf = windonshore_cf.iloc[3:, :2].reset_index(drop=True)

# change column names to datetime and CF_solar
windonshore_cf.columns = ["datetime", "CF_windonshore"]

# filter datatime between 2024-01-01 and 2024-12-31
windonshore_cf = windonshore_cf[(windonshore_cf["datetime"] >= "2024-01-01") & (windonshore_cf["datetime"] <= "2024-12-31")].reset_index(drop=True)
windonshore_cf.head()

                    datetime CF_windonshore
0  2024-01-01 00:00:00+00:00       0.231344
1  2024-01-01 01:00:00+00:00       0.222525
2  2024-01-01 02:00:00+00:00       0.214007
3  2024-01-01 03:00:00+00:00       0.204727
4  2024-01-01 04:00:00+00:00       0.196597

In [9]:
# load wind offshore capacity factor data from CSV
windoffshore_cf = pd.read_csv("./WindOffshore_CF_2024.csv")
windoffshore_cf.head()

C:\Users\yaowa\AppData\Local\Temp\ipykernel_30200\2996865825.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  windoffshore_cf = pd.read_csv("./WindOffshore_CF_2024.csv")

,"# Renewables.ninja Wind (current offshore fleet, country zones, hourly, 1980 - 2024) - Spain - ninja_wind_countryzones_hourly_ES_current-offshore_merra2.csv - Version 1.4 - License: https://creativecommons.org/licenses/by-nc/4.0/ - Reference: https://doi.org/10.1016/j.energy.2016.08.068",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,# Units: time in UTC; other columns are capaci...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"# {'units': {'time': 'UTC', 'NATIONAL': 'bias-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,time,NATIONAL,ES11,ES12,ES13,ES21,ES22,ES23,ES24,ES30,...,ES42,ES43,ES51,ES52,ES53,ES61,ES62,ES63,ES64,ES70
3,1980-01-01 00:00:00+00:00,0.917527,NaN,NaN,NaN,0.917528,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1980-01-01 01:00:00+00:00,0.970495,NaN,NaN,NaN,0.970497,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# drop first three rows, and keep only first two columns
windoffshore_cf = windoffshore_cf.iloc[3:, :2].reset_index(drop=True)

# change column names to datetime and CF_solar
windoffshore_cf.columns = ["datetime", "CF_windoffshore"]

# filter datatime between 2024-01-01 and 2024-12-31
windoffshore_cf = windoffshore_cf[(windoffshore_cf["datetime"] >= "2024-01-01") & (windoffshore_cf["datetime"] <= "2024-12-31")].reset_index(drop=True)
windoffshore_cf.head()

                    datetime CF_windoffshore
0  2024-01-01 00:00:00+00:00          0.7632
1  2024-01-01 01:00:00+00:00        0.776559
2  2024-01-01 02:00:00+00:00        0.742909
3  2024-01-01 03:00:00+00:00        0.673741
4  2024-01-01 04:00:00+00:00          0.6226

In [11]:
# merge solar_cf and windonshore_cf on datetime
solar_wind_2024 = pd.merge(solar_cf, windonshore_cf, on="datetime")
solar_wind_2024 = pd.merge(solar_wind_2024, windoffshore_cf, on="datetime")
solar_wind_2024.head()

                    datetime CF_solar CF_windonshore CF_windoffshore
0  2024-01-01 00:00:00+00:00      0.0       0.231344          0.7632
1  2024-01-01 01:00:00+00:00      0.0       0.222525        0.776559
2  2024-01-01 02:00:00+00:00      0.0       0.214007        0.742909
3  2024-01-01 03:00:00+00:00      0.0       0.204727        0.673741
4  2024-01-01 04:00:00+00:00      0.0       0.196597          0.6226

### Hydro power

In [2]:
# load hydro data
hydro = pd.read_csv("./RealHydroMonthly_2024.csv", sep=';')
hydro.head()

,id,name,geoid,geoname,value,datetime
0,546,Real time generation hydro,NaN,NaN,4894.245744,2024-01-01T00:00:00+01:00
1,546,Real time generation hydro,NaN,NaN,3885.152179,2024-02-01T00:00:00+01:00
2,546,Real time generation hydro,NaN,NaN,5621.071781,2024-03-01T00:00:00+01:00
3,546,Real time generation hydro,NaN,NaN,5159.732060,2024-04-01T00:00:00+02:00
4,546,Real time generation hydro,NaN,NaN,3431.464606,2024-05-01T00:00:00+02:00

In [3]:
# add one column 'installed_capacity', 'capacity factor' calculated as value / installed_capacity
hydro["installed_capacity"] = 17077
hydro["CF_hydro"] = hydro["value"] / hydro["installed_capacity"]
hydro.head()

,id,name,geoid,geoname,value,datetime,installed_capacity,CF_hydro
0,546,Real time generation hydro,NaN,NaN,4894.245744,2024-01-01T00:00:00+01:00,17077,0.286599
1,546,Real time generation hydro,NaN,NaN,3885.152179,2024-02-01T00:00:00+01:00,17077,0.227508
2,546,Real time generation hydro,NaN,NaN,5621.071781,2024-03-01T00:00:00+01:00,17077,0.329160
3,546,Real time generation hydro,NaN,NaN,5159.732060,2024-04-01T00:00:00+02:00,17077,0.302145
4,546,Real time generation hydro,NaN,NaN,3431.464606,2024-05-01T00:00:00+02:00,17077,0.200941

In [4]:
hydro_cf = hydro[["datetime", "CF_hydro"]]

# Parse datetimes; handle timezone-aware strings by parsing with utc=True
hydro_cf["datetime"] = pd.to_datetime(hydro_cf["datetime"], errors="coerce", utc=True)
hydro_cf["datetime"] = hydro_cf["datetime"].dt.tz_convert("Europe/Madrid").dt.tz_localize(None)
hydro_cf.head()

C:\Users\yaowa\AppData\Local\Temp\ipykernel_30200\1894073553.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hydro_cf["datetime"] = pd.to_datetime(hydro_cf["datetime"], errors="coerce", utc=True)
C:\Users\yaowa\AppData\Local\Temp\ipykernel_30200\1894073553.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hydro_cf["datetime"] = hydro_cf["datetime"].dt.tz_convert("Europe/Madrid").dt.tz_localize(None)

    datetime  CF_hydro
0 2024-01-01  0.286599
1 2024-02-01  0.227508
2 2024-03-01  0.329160
3 2024-04-01  0.302145
4 2024-05-01  0.200941

In [12]:
solar_wind_2024['year_month'] = pd.to_datetime(solar_wind_2024['datetime']).dt.to_period('M')
hydro_cf['year_month'] = pd.to_datetime(hydro_cf['datetime']).dt.to_period('M')

# Merge on year_month
renewables_2024 = pd.merge(
    solar_wind_2024, 
    hydro_cf[['year_month', 'CF_hydro']], 
    on='year_month', 
    how='left'
)

# Drop the temporary year_month column
renewables_2024 = renewables_2024.drop(columns=['year_month'])

renewables_2024.head()

C:\Users\yaowa\AppData\Local\Temp\ipykernel_30200\3538911047.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  solar_wind_2024['year_month'] = pd.to_datetime(solar_wind_2024['datetime']).dt.to_period('M')
C:\Users\yaowa\AppData\Local\Temp\ipykernel_30200\3538911047.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hydro_cf['year_month'] = pd.to_datetime(hydro_cf['datetime']).dt.to_period('M')

                    datetime CF_solar CF_windonshore CF_windoffshore  CF_hydro
0  2024-01-01 00:00:00+00:00      0.0       0.231344          0.7632  0.286599
1  2024-01-01 01:00:00+00:00      0.0       0.222525        0.776559  0.286599
2  2024-01-01 02:00:00+00:00      0.0       0.214007        0.742909  0.286599
3  2024-01-01 03:00:00+00:00      0.0       0.204727        0.673741  0.286599
4  2024-01-01 04:00:00+00:00      0.0       0.196597          0.6226  0.286599

In [13]:
renewables_2024.shape

(8760, 5)

In [14]:
# delete rows with same datetime, keep the first occurrence
renewables_df_year = renewables_2024.drop_duplicates(subset=["datetime"], keep="first")
renewables_df_year.shape

(8760, 5)

In [15]:
renewables_df_year = renewables_df_year[["datetime", "CF_solar", "CF_windonshore", "CF_windoffshore", "CF_hydro"]].rename(columns={"CF_solar": "NLD", "CF_windonshore": "NLD1", "CF_windoffshore": "NLD2", "CF_hydro": "NLD3"})
renewables_df_year.head()

                    datetime  NLD      NLD1      NLD2      NLD3
0  2024-01-01 00:00:00+00:00  0.0  0.231344    0.7632  0.286599
1  2024-01-01 01:00:00+00:00  0.0  0.222525  0.776559  0.286599
2  2024-01-01 02:00:00+00:00  0.0  0.214007  0.742909  0.286599
3  2024-01-01 03:00:00+00:00  0.0  0.204727  0.673741  0.286599
4  2024-01-01 04:00:00+00:00  0.0  0.196597    0.6226  0.286599

In [16]:
renewables_df_year.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  8760 non-null   object
 1   NLD       8760 non-null   object
 2   NLD1      8760 non-null   object
 3   NLD2      8760 non-null   object
 4   NLD3      8760 non-null   float64
dtypes: float64(1), object(4)
memory usage: 342.3+ KB

In [17]:
renewables_df_year["datetime"] = pd.to_datetime(renewables_df_year["datetime"], errors="coerce")

In [18]:
renewables_df_year.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  8760 non-null   datetime64[ns, UTC]
 1   NLD       8760 non-null   object
 2   NLD1      8760 non-null   object
 3   NLD2      8760 non-null   object
 4   NLD3      8760 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(1), object(3)
memory usage: 342.3+ KB

In [19]:
# Format to match demand.csv
# First header rows as in demand.csv
header = pd.DataFrame({"nodes": ["techs"], "NLD": ["solar_pv"], "NLD1": ["wind_onshore"], "NLD2": ["wind_offshore"], "NLD3": ["hydro"]})

# Prepare final formatted time series
ts = pd.DataFrame({
    "nodes": renewables_df_year["datetime"].dt.strftime("%Y-%m-%d %H:%M:%S"),
    "NLD": renewables_df_year["NLD"],
    "NLD1": renewables_df_year["NLD1"],
    "NLD2": renewables_df_year["NLD2"],
    "NLD3": renewables_df_year["NLD3"]
})

# Combine them together
renewables_final_year = pd.concat([header, ts], ignore_index=True)


renewables_final_year.head(10)

                 nodes       NLD          NLD1           NLD2      NLD3
0                techs  solar_pv  wind_onshore  wind_offshore     hydro
1  2024-01-01 00:00:00       0.0      0.231344         0.7632  0.286599
2  2024-01-01 01:00:00       0.0      0.222525       0.776559  0.286599
3  2024-01-01 02:00:00       0.0      0.214007       0.742909  0.286599
4  2024-01-01 03:00:00       0.0      0.204727       0.673741  0.286599
5  2024-01-01 04:00:00       0.0      0.196597         0.6226  0.286599
6  2024-01-01 05:00:00       0.0      0.192137       0.630086  0.286599
7  2024-01-01 06:00:00       0.0      0.194536       0.645159  0.286599
8  2024-01-01 07:00:00       0.0      0.204508        0.63155  0.286599
9  2024-01-01 08:00:00     0.048      0.198421       0.622468  0.286599

In [20]:
# change the name of NLD1 to NLD
renewables_final_year = renewables_final_year.rename(columns={"NLD1": "NLD", "NLD2": "NLD", "NLD3": "NLD"})
renewables_final_year.head()

                 nodes       NLD           NLD            NLD       NLD
0                techs  solar_pv  wind_onshore  wind_offshore     hydro
1  2024-01-01 00:00:00       0.0      0.231344         0.7632  0.286599
2  2024-01-01 01:00:00       0.0      0.222525       0.776559  0.286599
3  2024-01-01 02:00:00       0.0      0.214007       0.742909  0.286599
4  2024-01-01 03:00:00       0.0      0.204727       0.673741  0.286599

In [21]:
renewables_final_year.tail()

                    nodes  NLD       NLD       NLD       NLD
8756  2024-12-30 19:00:00  0.0   0.09093  0.060125  0.174648
8757  2024-12-30 20:00:00  0.0  0.108659  0.104132  0.174648
8758  2024-12-30 21:00:00  0.0  0.121571   0.18936  0.174648
8759  2024-12-30 22:00:00  0.0   0.12688  0.301705  0.174648
8760  2024-12-30 23:00:00  0.0  0.131307  0.398101  0.174648

In [22]:
# Save to new CSV
renewables_final_year.to_csv("./renewables_year.csv", index=False)